prepare:
  test_size: 0.2
  random_state: 42
  sample_size: 50000  # Увеличено для лучшего обучения

train:
  model_type: "RandomForestClassifier"
  n_estimators: 100
  max_depth: 15
  random_state: 42
  max_features: "sqrt"
  
  tfidf_max_features: 5000
  ngram_range: [1, 2]
  min_df: 2
  max_df: 0.8
  
  max_iter: 1000
